# Generated by Django 4.2.9 on 2024-01-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Allan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="project/")),
                ("link", models.URLField()),
            ],
        ),
        migrations.DeleteModel(name="Portfolio",),
    ]
